import type { ChatThread, Jesta, Message, Offer, User } from "./types";

const now = Date.now();
const minsAgo = (m: number) => new Date(now - m * 60000).toISOString();
const hoursAgo = (h: number) => new Date(now - h * 3600000).toISOString();
const daysAgo = (d: number) => new Date(now - d * 86400000).toISOString();

export const USERS: User[] = [
  {
    id: "u1",
    name: "מיכל",
    avatar: "https://i.pravatar.cc/150?u=michal",
    rating: 4.9,
    ratingCount: 128,
    verified: true,
    online: true,
    bio: "שכנה מתל אביב, תמיד שמחה לעזור",
    tags: ["נתנה ג'סטה אתמול", "12 עזרה בדלק", "x8 הובלה קלה", "מגיבה מהר", "שכנה אמינה"],
    stats: { given: 47, requested: 11, avgResponseMin: 6 },
    helpCategories: ["fuel", "moving", "errands", "neighborhood", "home", "pets"],
    distanceM: 180,
    lastActive: "עכשיו",
  },
  {
    id: "u2",
    name: "דניאל",
    avatar: "https://i.pravatar.cc/150?u=daniel",
    rating: 4.9,
    ratingCount: 64,
    verified: true,
    online: true,
    tags: ["עזר אתמול", "דלק"],
    stats: { given: 22, requested: 8, avgResponseMin: 12 },
    helpCategories: ["fuel", "digital"],
    distanceM: 800,
    lastActive: "לפני 5 דק׳",
  },
  {
    id: "u3",
    name: "נועה ש.",
    avatar: "https://i.pravatar.cc/150?u=noa",
    rating: 4.9,
    ratingCount: 41,
    verified: true,
    online: true,
    tags: ["דלק", "עזר אתמול"],
    stats: { given: 5, requested: 3, avgResponseMin: 8 },
    helpCategories: ["fuel", "home"],
    distanceM: 180,
    lastActive: "עכשיו",
  },
  {
    id: "u4",
    name: "איתן ל.",
    avatar: "https://i.pravatar.cc/150?u=eitan",
    rating: 4.8,
    ratingCount: 33,
    verified: true,
    online: false,
    tags: ["הובלה קלה", "5 ג'סטות החודש"],
    stats: { given: 18, requested: 4, avgResponseMin: 15 },
    helpCategories: ["moving", "home", "garden"],
    distanceM: 420,
    lastActive: "לפני שעה",
  },
  {
    id: "u5",
    name: "יוסי",
    avatar: "https://i.pravatar.cc/150?u=yossi",
    rating: 4.7,
    ratingCount: 19,
    verified: true,
    online: true,
    tags: ["שכן אמין"],
    stats: { given: 9, requested: 6, avgResponseMin: 20 },
    helpCategories: ["home", "neighborhood"],
    distanceM: 400,
    lastActive: "עכשיו",
  },
  {
    id: "u6",
    name: "איתי",
    avatar: "https://i.pravatar.cc/150?u=itay",
    rating: 4.7,
    ratingCount: 27,
    verified: true,
    online: true,
    tags: ["מגיב מהר"],
    stats: { given: 14, requested: 2, avgResponseMin: 5 },
    helpCategories: ["fuel", "errands"],
    distanceM: 1600,
    lastActive: "עכשיו",
  },
  {
    id: "u7",
    name: "שירה",
    avatar: "https://i.pravatar.cc/150?u=shira",
    rating: 5.0,
    ratingCount: 12,
    verified: false,
    online: false,
    tags: ["גינה", "חיות מחמד"],
    stats: { given: 7, requested: 5, avgResponseMin: 25 },
    helpCategories: ["garden", "pets"],
    distanceM: 2500,
    lastActive: "אתמול",
  },
  {
    id: "u-me",
    name: "אני (דמו)",
    avatar: "https://i.pravatar.cc/150?u=demo",
    rating: 4.8,
    ratingCount: 15,
    verified: true,
    online: true,
    tags: ["משתמש דמו"],
    stats: { given: 3, requested: 2, avgResponseMin: 10 },
    helpCategories: ["fuel", "home", "errands"],
    distanceM: 0,
    lastActive: "עכשיו",
  },
];

export const JESTAS: Jesta[] = [
  {
    id: "j1",
    title: "נגמר לי הדלק ליד איילון",
    description:
      "אני בדרך לאיילון צפונה, הדלק נגמר לי ממש עכשיו. אשמח לעזרה עם כמה ליטרים עד לתחנה הקרובה.",
    category: "fuel",
    authorId: "u2",
    locationLabel: "תל אביב, אזור איילון",
    lat: 32.074,
    lng: 34.792,
    distanceM: 800,
    urgency: "now",
    status: "open",
    createdAt: minsAgo(12),
    offerIds: ["o1", "o2"],
    respondersCount: 2,
  },
  {
    id: "j2",
    title: "צריכה עזרה להרים מקרר לקומה 2",
    description:
      "יש לי מקרר חדש למטה בבניין וצריכה מישהו שיעזור להרים לקומה 2. בערך 10 דקות עבודה.",
    category: "moving",
    authorId: "u3",
    locationLabel: "תל אביב, הצפון הישן",
    lat: 32.085,
    lng: 34.781,
    distanceM: 1200,
    urgency: "today",
    status: "open",
    createdAt: hoursAgo(1),
    offerIds: [],
    respondersCount: 0,
  },
  {
    id: "j3",
    title: "מישהו יכול להחזיק מדף 5 דקות?",
    description: "מתקינה מדף במטבח וצריכה מישהו שיחזיק אותו בזמן שאני מקדחת. 5 דקות בלבד!",
    category: "home",
    authorId: "u5",
    locationLabel: "תל אביב, רמת אביב",
    lat: 32.113,
    lng: 34.801,
    distanceM: 400,
    urgency: "now",
    status: "open",
    createdAt: hoursAgo(3),
    offerIds: [],
    respondersCount: 0,
  },
  {
    id: "j4",
    title: "קניות קצרות למבוגר בשכונה",
    description: "שכן מבוגר צריך עזרה עם קניות קטנות מהסופר ברחוב. שקיות קלות, כ-20 דקות.",
    category: "errands",
    authorId: "u4",
    locationLabel: "תל אביב, פלורנטין",
    lat: 32.056,
    lng: 34.769,
    distanceM: 2100,
    urgency: "today",
    status: "open",
    createdAt: hoursAgo(5),
    offerIds: [],
    respondersCount: 1,
  },
  {
    id: "j5",
    title: "השקיית עציצים בזמן חופשה",
    description: "יוצאת לחופשה ל-4 ימים, מישהו יכול להשקות 3 עציצים במרפסת? מפתח אצל השכן.",
    category: "garden",
    authorId: "u7",
    locationLabel: "תל אביב, נווה צדק",
    lat: 32.06,
    lng: 34.765,
    distanceM: 2800,
    urgency: "flexible",
    status: "open",
    createdAt: daysAgo(1),
    offerIds: [],
    respondersCount: 0,
  },
  {
    id: "j6",
    title: "טיול קצר לכלב הערב",
    description: "נתקעתי בעבודה עד מאוחר, מישהו יכול לקחת את בנדי (גולדן רטריבר ידידותי) לטיול קצר?",
    category: "pets",
    authorId: "u6",
    locationLabel: "תל אביב, הצפון החדש",
    lat: 32.09,
    lng: 34.785,
    distanceM: 950,
    urgency: "today",
    status: "open",
    createdAt: minsAgo(45),
    offerIds: [],
    respondersCount: 0,
  },
  {
    id: "j7",
    title: "עזרה בהגדרת WiFi לאימא",
    description: "אימא שלי צריכה עזרה בהגדרת הראוטר החדש. מישהו טוב בזה באזור?",
    category: "digital",
    authorId: "u3",
    locationLabel: "תל אביב, יד אליהו",
    lat: 32.055,
    lng: 34.79,
    distanceM: 3200,
    urgency: "flexible",
    status: "open",
    createdAt: hoursAgo(8),
    offerIds: [],
    respondersCount: 0,
  },
  {
    id: "j8",
    title: "שיתוף סולם לתיקון תריס",
    description: "צריך סולם גבוה לתיקון תריס בקומה ראשונה. אחזיר תוך שעה.",
    category: "neighborhood",
    authorId: "u5",
    locationLabel: "תל אביב, לב העיר",
    lat: 32.07,
    lng: 34.775,
    distanceM: 600,
    urgency: "now",
    status: "open",
    createdAt: minsAgo(30),
    offerIds: [],
    respondersCount: 0,
  },
];

export const OFFERS: Offer[] = [
  {
    id: "o1",
    jestaId: "j1",
    userId: "u1",
    message: "יש לי ג'ריקן במכונית, יכולה להגיע תוך 10 דק׳",
    createdAt: minsAgo(8),
  },
  {
    id: "o2",
    jestaId: "j1",
    userId: "u6",
    message: "אני בדרך, אשמח לעזור",
    createdAt: minsAgo(5),
  },
];

export const THREADS: ChatThread[] = [
  {
    id: "t1",
    jestaId: "j1",
    participantIds: ["u-me", "u1"],
    lastMessageAt: minsAgo(2),
    unreadCount: 2,
  },
  {
    id: "t2",
    jestaId: "j2",
    participantIds: ["u-me", "u3"],
    lastMessageAt: hoursAgo(2),
    unreadCount: 0,
  },
];

export const MESSAGES: Message[] = [
  {
    id: "m1",
    threadId: "t1",
    senderId: "u1",
    text: "היי, אני 10 דקות ממך עם ג'ריקן",
    createdAt: minsAgo(22),
    read: true,
  },
  {
    id: "m2",
    threadId: "t1",
    senderId: "u-me",
    text: "מדהים, אני ליד תחנת הדלק בכביש",
    createdAt: minsAgo(21),
    read: true,
  },
  {
    id: "m3",
    threadId: "t1",
    senderId: "u1",
    text: "סבבה, אגיע במכונית כחולה",
    createdAt: minsAgo(20),
    read: false,
  },
  {
    id: "m4",
    threadId: "t2",
    senderId: "u-me",
    text: "היי נועה, ראיתי את הבקשה — מתי נוח?",
    createdAt: hoursAgo(2),
    read: true,
  },
  {
    id: "m5",
    threadId: "t2",
    senderId: "u3",
    text: "תודה! היום אחר הצהריים מושלם",
    createdAt: hoursAgo(2),
    read: true,
  },
];

export const CURRENT_USER_ID = "u-me";
